line-length = 120
unsafe-fixes = true

[lint]
# We enable all rules by default, including any added in the future, then only disable the ones we don't want
# See: https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
    "BLE001",  # Do not catch blind exception: `Exception`
    "CPY001",  # Missing copyright notice at top of file
    "D100",    # Missing docstring in public module
    "D212",    # Multi-line docstring summary should start at the first line
    "S608",    # Possible SQL injection vector through string-based query construction (NOTE: this complains about f-strings)
    "TC002",   # Move third-party import `...` into a type-checking block (NOTE: This avoids runtime errors with Pydantic)
]

[lint.per-file-ignores]
"tests/**" = [
    "S101"  # Use of `assert` detected
]

[lint.pydocstyle]
convention = "google"
